export default[
    {
        id:1,
        img:'/images/icons8-hamburger-90.png',
        name:'CheeseBurger',
        price:'140000T'
    },
    {
        id:2,
        img:'/images/icons8-hamburger-90.png',
        name:'DoubleBurger',
        price:'190000T'
    },
    {
        id:3,
        img:'/images/icons8-hamburger-90.png',
        name:'ChorizzoBurger',
        price:'165000T'
    },
    {
        id:4,
        img:'/images/icons8-hamburger-90.png',
        name:'ChickenBurger',
        price:'120000T'
    },
    {
        id:5,
        img:'/images/icons8-hamburger-90.png',
        name:'FishBurger',
        price:'160000T'
    },

]