export default[
    {
        id:1,
        img:'/images/icons8-pizza-100.png',
        name:'peperoni',
        price:'180000'
    },
    {
        id:2,
        img:'/images/icons8-pizza-100.png',
        name:'manzo',
        price:'230000'
    },
    {
        id:3,
        img:'/images/icons8-pizza-100.png',
        name:'Unani',
        price:'165000'
    },
    {
        id:4,
        img:'/images/icons8-pizza-100.png',
        name:'gushtoQarch',
        price:'240000'
    },
    {
        id:5,
        img:'/images/icons8-pizza-100.png',
        name:'MorqoQarch',
        price:'210000'
    },

]